from ast import Bytes
from sqlalchemy import Integer, String, Float, DateTime, Table, Column
from app.config.connection_db import meta

patient_features = Table(
    'patient_features', meta,
    Column('patient_id', Integer, primary_key=True),
    Column('S_MaxPerfusion', Float(8, 3)),
    Column('S_Intervals', Integer),
    Column('S_ED', Integer),
    Column('S_ES', Integer),
    Column('S_EF', Integer),

    Column('SM_LADPerfusion', Float(8, 3)),
    Column('SSD_LADPerfusion', Float(8, 3)),
    Column('SM_LCXPerfusion', Float(8, 3)),
    Column('SSD_LCXPerfusion', Float(8, 3)),
    Column('SM_RCAPerfusion', Float(8, 3)),
    Column('SSD_RCAPerfusion', Float(8, 3)),
    Column('SM_TOTPerfusion', Float(8, 3)),
    Column('SSD_TOTPerfusion', Float(8, 3)),
    Column('SM_LADWallThickening', Float(8, 3)),
    Column('SSD_LADWallThickening', Float(8, 3)),
    Column('SM_LCXWallThickening', Float(8, 3)),
    Column('SSD_LCXWallThickening', Float(8, 3)),
    Column('SM_RCAWallThickening', Float(8, 3)),
    Column('SSD_RCAWallThickening', Float(8, 3)),
    Column('SM_TOTWallThickening', Float(8, 3)),
    Column('SSD_TOTWallThickening', Float(8, 3)),
    Column('SM_LADWallMotion', Float(8, 3)),
    Column('SSD_LADWallMotion', Float(8, 3)),
    Column('SM_LCXWallMotion', Float(8, 3)),
    Column('SSD_LCXWallMotion', Float(8, 3)),
    Column('SM_RCAWallMotion', Float(8, 3)),
    Column('SSD_RCAWallMotion', Float(8, 3)),
    Column('SM_TOTWallMotion', Float(8, 3)),
    Column('SSD_TOTWallMotion', Float(8, 3)),

    Column('SE_LADPerfusion', Integer),
    Column('SE_LCXPerfusion', Integer),       
    Column('SE_RCAPerfusion', Integer),
    Column('SE_TOTPerfusion', Integer),
    Column('SE_LADWallThickening', Integer),
    Column('SE_LCXWallThickening', Integer),
    Column('SE_RCAWallThickening', Integer),
    Column('SE_TOTWallThickening', Integer),
    Column('SE_LADWallMotion', Integer),
    Column('SE_LCXWallMotion', Integer),
    Column('SE_RCAWallMotion', Integer),
    Column('SE_TOTWallMotion', Integer),

    Column('SSEV_LADPerfusion', Float(8, 3)),
    Column('SSEV_LCXPerfusion', Float(8, 3)),       
    Column('SSEV_RCAPerfusion', Float(8, 3)),
    Column('SSEV_TOTPerfusion', Float(8, 3)),
    Column('SSEV_LADWallThickening', Float(8, 3)),
    Column('SSEV_LCXWallThickening', Float(8, 3)),
    Column('SSEV_RCAWallThickening', Float(8, 3)),
    Column('SSEV_TOTWallThickening', Float(8, 3)),
    Column('SSEV_LADWallMotion', Float(8, 3)),
    Column('SSEV_LCXWallMotion', Float(8, 3)),
    Column('SSEV_RCAWallMotion', Float(8, 3)),
    Column('SSEV_TOTWallMotion', Float(8, 3)),

    Column('R_MaxPerfusion', Integer),
    Column('R_Intervals', Integer),
    Column('R_ED', Integer),
    Column('R_ES', Integer),
    Column('R_EF', Integer),

    Column('RM_LADPerfusion', Float(8, 3)),
    Column('RSD_LADPerfusion', Float(8, 3)),
    Column('RM_LCXPerfusion', Float(8, 3)),
    Column('RSD_LCXPerfusion', Float(8, 3)),   
    Column('RM_RCAPerfusion', Float(8, 3)),
    Column('RSD_RCAPerfusion', Float(8, 3)),
    Column('RM_TOTPerfusion', Float(8, 3)),
    Column('RSD_TOTPerfusion', Float(8, 3)),

    Column('RM_LADWallThickening', Float(8, 3)),
    Column('RSD_LADWallThickening', Float(8, 3)),

    Column('RM_LCXWallThickening', Float(8, 3)),
    Column('RSD_LCXWallThickening', Float(8, 3)),

    Column('RM_RCAWallThickening', Float(8, 3)),
    Column('RSD_RCAWallThickening', Float(8, 3)),

    Column('RM_TOTWallThickening', Float(8, 3)),
    Column('RSD_TOTWallThickening', Float(8, 3)),

    Column('RM_LADWallMotion', Float(8, 3)),
    Column('RSD_LADWallMotion', Float(8, 3)),

    Column('RM_LCXWallMotion', Float(8, 3)),
    Column('RSD_LCXWallMotion', Float(8, 3)),

    Column('RM_RCAWallMotion', Float(8, 3)),
    Column('RSD_RCAWallMotion', Float(8, 3)),

    Column('RM_TOTWallMotion', Float(8, 3)),
    Column('RSD_TOTWallMotion', Float(8, 3)),

    Column('RE_LADPerfusion', Integer),      
    Column('RE_LCXPerfusion', Integer),
    Column('RE_RCAPerfusion', Integer),
    Column('RE_TOTPerfusion', Integer),
    Column('RE_LADWallThickening', Integer),
    Column('RE_LCXWallThickening', Integer),
    Column('RE_RCAWallThickening', Integer),
    Column('RE_TOTWallThickening', Integer),
    Column('RE_LADWallMotion', Integer),
    Column('RE_LCXWallMotion', Integer),
    Column('RE_RCAWallMotion', Integer),
    Column('RE_TOTWallMotion', Integer),

    Column('RSEV_LADPerfusion', Float(8, 3)),      
    Column('RSEV_LCXPerfusion', Float(8, 3)),
    Column('RSEV_RCAPerfusion', Float(8, 3)),
    Column('RSEV_TOTPerfusion', Float(8, 3)),
    Column('RSEV_LADWallThickening', Float(8, 3)),
    Column('RSEV_LCXWallThickening', Float(8, 3)),
    Column('RSEV_RCAWallThickening', Float(8, 3)),
    Column('RSEV_TOTWallThickening', Float(8, 3)),
    Column('RSEV_LADWallMotion', Float(8, 3)),
    Column('RSEV_LCXWallMotion', Float(8, 3)),
    Column('RSEV_RCAWallMotion', Float(8, 3)),
    Column('RSEV_TOTWallMotion', Float(8, 3)),

    Column('SSS', Integer),
    Column('S_STS', Integer),       
    Column('S_SMS', Integer),
    Column('SRS', Integer),
    Column('R_STS', Integer),
    Column('R_SMS', Integer),
    Column('R_SMS', Integer),
    Column('age', Integer),
    Column('gender', String),
    Column('bmi', Float(8, 3)),
    Column('dm', Integer),
    Column('ht', Integer),
    Column('dlp', Integer),
    Column('ckd', Integer),      
)
