apiVersion: 1
datasources:
  - name: image_logging_model
    type: marcusolsson-csv-datasource
    editable: true
    url: /airflow/dags/log_train_model/log_train_quantitative_model.csv
    jsonData:
      storage: local

  - name: mibi_db
    type: mysql
    url: mibi_db:3306
    database: mpi_project
    user: admin
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
      storage: local
    secureJsonData:
      password: admin
      isDefault: true